### ISSUE TITLE
Aggiungere nuove coordinate gps ai progetti

### ISSUE THREAD

**Issue by filipic** [DeppSRL/open_ricostruzione#106]
Sono state fornite alcune coord. geografiche (lat/long) per i progetti che ne erano sprovvisti.
Va pensato l'inserimento di questi dati anche in considerazione dell'ultimo aggiornamento pervenuto dei dati fenice.
Allegato il file con le coordinate (ultime due colonne), memorizzato, in formato csv e txt, anche nella cartella dati di gdrive

[nuove_coord_gps_progetti.txt](https://github.com/DeppSRL/open_ricostruzione/files/7603/nuove_coord_gps_progetti.txt)

**Comment by verganis** [comment]
Nota bene: il file allegato ha i valori LAT/LONG scambiati.
il file corretto e completo e' stato caricato su Drive
