### ISSUE TITLE
Aggiungere disclaimer cookies

### ISSUE THREAD

**Issue by verganis** [DeppSRL/open_ricostruzione#57]
base http://www.opencoesione.gov.it/note-legali/

**Comment by filipic** [comment]
Open Ricostruzione utilizza cookie tecnici e, con il consenso degli utenti, cookie analytics e di terze parti per rendere migliore la navigazione e per fornire alcune funzionalità aggiuntive quali la condivisione sui social media. La prosecuzione nella navigazione, cliccando in un altro punto dello schermo o effettuando un’azione di scroll, equivale a prestazione del consenso.
